#!/usr/bin/env bash

set -e
set -x

function do_loop() {
    if [ "$#" -gt 0 ]; then
        for p in "$@"; do
            echo $p
        done

    else
        echo "meh"
    fi
}

function method1() {
    (
        echo "foo"
    )
}

function main() {

    case $1 in
    "method1")
        method1
        ;;
    *)
        echo "Not a valid method."
        ;;
    esac
}

main "$@"
